apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: keda-aws-sqs-sample
spec:
  scaleTargetRef:
    deploymentName: keda-aws-sqs-python
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://us-west-2.queue.amazonaws.com/463674642148/keda-test
      region: "us-west-2"
      awsAccessKeyID: AWS_ACCESS_KEY_ID
      awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
      queueLength: "5"